Round 2

diff --git a/lib/tools/po/GNUmakefile.inc b/lib/tools/po/GNUmakefile.inc
--- a/lib/tools/po/GNUmakefile.inc
+++ b/lib/tools/po/GNUmakefile.inc
@@ -22,14 +22,12 @@ APPLICATION ?= $(shell basename "$(TYPE_DIR)")_$(shell basename "$(MODULE_DIR)")
 PHP ?= php
 
 # Let PHP parse the config.php file to get the g2data directory.
-G2DATA = $(shell echo '<?php require '$(GALLERYDIR)/lib/support/GallerySetupUtilities.class';
-$$gallery = new GallerySetupUtilitiesStub();
-@require '$(GALLERYDIR)/config.php';
-echo $$gallery->getConfig('data.gallery.base'); ?>' | $(PHP) -q 2>&1)
+G2DATA = $(shell echo '<?php include "$(GALLERYDIR)/lib/support/GallerySetupUtilities.class"; $$gallery = new GallerySetupUtilitiesStub(); @include "$(GALLERYDIR)/config.php"; echo $$gallery->getConfig("data.gallery.base"); ?>' | $(PHP) -q 2>&1)
 
-MSGFMT_FLAGS = 
-ifndef QUIET
-	MSGFMT_FLAGS = -v
+ifdef QUIET
+    MSGFMT_FLAGS =
+else
+    MSGFMT_FLAGS = -v
 endif
 
 MSGFMT = msgfmt $(MSGFMT_FLAGS) -c -o
@@ -58,14 +56,14 @@ messages.po: alwaysbuild
 	@perl "$(TOOLDIR)"/po/premerge-messages.pl $@ messages.po > messages.tmp
 	@# ignore errors from msgmerge, we'll catch them on the msgfmt command:
 	@-if [ -s messages.tmp ]; then \
-		msgmerge --quiet --width=95 $(COMPENDIUM) $@ messages.tmp > $@.tmp; \
-		if [ -s $@.tmp ]; then mv $@.tmp $@; else $(RM) $@.tmp; fi; \
-		perl -pi "$(TOOLDIR)"/po/header.pl $@; \
+	    msgmerge --quiet --width=95 $(COMPENDIUM) $@ messages.tmp > $@.tmp; \
+	    if [ -s $@.tmp ]; then mv $@.tmp $@; else $(RM) $@.tmp; fi; \
+	    perl -pi "$(TOOLDIR)"/po/header.pl $@; \
 	  elif [ -z "$(NOCREATE)" ]; then \
-		if [ -n "$(LANGPO)" ]; then \
-		  perl "$(TOOLDIR)"/po/premerge-messages.pl -2 messages.po $(LANGPO) > $@; \
-		else cp messages.po $@; fi; \
-		perl -pi "$(TOOLDIR)"/po/header.pl $@; \
+	    if [ -n "$(LANGPO)" ]; then \
+	      perl "$(TOOLDIR)"/po/premerge-messages.pl -2 messages.po $(LANGPO) > $@; \
+	    else cp messages.po $@; fi; \
+	    perl -pi "$(TOOLDIR)"/po/header.pl $@; \
 	  fi
 	@$(RM) messages.tmp
 
@@ -78,94 +76,94 @@ update: $(PO).po
 
 check-g2data:
 	@if ! test -d '$(G2DATA)'; then \
-		echo "************************************************************"; \
-		echo "WARNING: We detected the following as your g2data dir but"; \
-		echo "this directory does not appear to exist.  We will be unable"; \
-		echo "to copy new .mo files into the g2data/locale directory until"; \
-		echo "this is fixed."; \
-		echo ""; \
-		echo '$(G2DATA)'; \
-		echo ""; \
-		echo "Alternatively, point your browser at gallery2/lib/support, "; \
-		echo "click the \"Filesystem Permissions\" link and then click "; \
-		echo "the 'Make the locale folder read/write' link"; \
-		echo "************************************************************"; \
+	    echo "************************************************************"; \
+	    echo "WARNING: We detected the following as your g2data dir but"; \
+	    echo "this directory does not appear to exist.  We will be unable"; \
+	    echo "to copy new .mo files into the g2data/locale directory until"; \
+	    echo "this is fixed."; \
+	    echo ""; \
+	    echo '$(G2DATA)'; \
+	    echo ""; \
+	    echo "Alternatively, point your browser at gallery2/lib/support, "; \
+	    echo "click the \"Filesystem Permissions\" link and then click "; \
+	    echo "the 'Make the locale folder read/write' link"; \
+	    echo "************************************************************"; \
 	fi
 
 install: check-g2data update
 	@if ! test -z "$(DEBUG)"; then set -x; fi; \
 	if test "$(OSTYPE)" = "solaris"; then \
-		echo "You'll probably get some warnings on Solaris. This is normal."; \
-		MSGFMT_CMD="$(MSGFMTSOL)"; \
+	    echo "You'll probably get some warnings on Solaris. This is normal."; \
+	    MSGFMT_CMD="$(MSGFMTSOL)"; \
 	else \
-		MSGFMT_CMD="$(MSGFMT)"; \
+	    MSGFMT_CMD="$(MSGFMT)"; \
 	fi; \
 	FAIL=0; \
 	COPY_FAIL=0; \
 	echo "Updating $(PO)"; \
 	for LOCALE in `ls $(PO).po | grep -v messages.po | sed 's/\.[^.]*$$//g'`; do \
-		INSTALL_FILE=""; \
-		if test -z "$${QUIET}"; then echo $${LOCALE}; fi; \
-		if test -d ../locale; then \
+	    INSTALL_FILE=""; \
+	    if test -z "$${QUIET}"; then echo $${LOCALE}; fi; \
+	    if test -d ../locale; then \
 		if ! "$(TOOLDIR)"/po/shtool mkdir -p ../locale/$${LOCALE}/LC_MESSAGES; then \
-			echo "Could not create directory: ../locale/$${LOCALE}/LC_MESSAGES"; \
-			exit 1; \
+		    echo "Could not create directory: ../locale/$${LOCALE}/LC_MESSAGES"; \
+		    exit 1; \
 		fi; \
 		MO_FILE=../locale/$${LOCALE}/LC_MESSAGES/$(APPLICATION).mo; \
-		elif test "$(APPLICATION)" = "gallery2_install" \
+	    elif test "$(APPLICATION)" = "gallery2_install" \
 		   || test "$(APPLICATION)" = "gallery2_upgrade";  then \
 		if ! $(TOOLDIR)/po/shtool mkdir -p ../../locale/$${LOCALE}/LC_MESSAGES; then \
-			echo "Could not create directory: ../../locale/$${LOCALE}/LC_MESSAGES"; \
-			exit 1; \
+		    echo "Could not create directory: ../../locale/$${LOCALE}/LC_MESSAGES"; \
+		    exit 1; \
 		fi; \
 		MO_FILE=../../locale/$${LOCALE}/LC_MESSAGES/$(APPLICATION).mo; \
-		else \
+	    else \
 		MO_FILE=$${LOCALE}.mo; \
 		if test -d '$(G2DATA)'; then \
-			INSTALL_DIR='$(G2DATA)'/locale/$${LOCALE}/LC_MESSAGES; \
-			INSTALL_FILE="$${INSTALL_DIR}/$(APPLICATION).mo"; \
+		    INSTALL_DIR='$(G2DATA)'/locale/$${LOCALE}/LC_MESSAGES; \
+		    INSTALL_FILE="$${INSTALL_DIR}/$(APPLICATION).mo"; \
 		fi; \
-		fi; \
-		$(PHP) -f $(TOOLDIR)/po/trim-po.php `pwd`/$${LOCALE}.po > tmp.po; \
-		if $${MSGFMT_CMD} $${MO_FILE} tmp.po; then \
+	    fi; \
+	    $(PHP) -f $(TOOLDIR)/po/trim-po.php `pwd`/$${LOCALE}.po > tmp.po; \
+	    if $${MSGFMT_CMD} $${MO_FILE} tmp.po; then \
 		if test -n "$${QUIET}"; then \
-			echo -n '.'; \
+		    echo -n '.'; \
 		fi; \
 		if test -n "$${INSTALL_FILE}"; then \
-			if ! test -d "$${INSTALL_DIR}"; then \
+		    if ! test -d "$${INSTALL_DIR}"; then \
 			echo ">> Creating $${INSTALL_DIR}"; \
 			if ! $(TOOLDIR)/po/shtool mkdir -p $${INSTALL_DIR}; then \
-				echo "** Unable to create $${INSTALL_DIR}!"; \
-				COPY_FAIL=1; \
+			    echo "** Unable to create $${INSTALL_DIR}!"; \
+			    COPY_FAIL=1; \
 			fi \
-			fi; \
-			if test -d "$${INSTALL_DIR}"; then \
+		    fi; \
+		    if test -d "$${INSTALL_DIR}"; then \
 			if cp $${MO_FILE} $${INSTALL_FILE}; then \
-				chmod 777 $${INSTALL_FILE} 2>/dev/null ; \
+			    chmod 777 $${INSTALL_FILE} 2>/dev/null ; \
 			else \
-				echo "** Unable to install $${INSTALL_FILE}!"; \
-				COPY_FAIL=1; \
+			    echo "** Unable to install $${INSTALL_FILE}!"; \
+			    COPY_FAIL=1; \
 			fi; \
-			fi \
+		    fi \
 		fi \
-		else \
+	    else \
 		echo -n "Fail: $${LOCALE}"; \
 		FAIL=1; \
-		fi; \
-		$(RM) tmp.po; \
-		if test -z "$${QUIET}"; then echo; fi; \
+	    fi; \
+	    $(RM) tmp.po; \
+	    if test -z "$${QUIET}"; then echo; fi; \
 	done; \
 	if test $${COPY_FAIL} -gt 0; then \
-		echo "************************************************************"; \
-		echo "WARNING: Failed to copy some .mo files to the g2data/locale"; \
-		echo "directory! Try changing the permissions on your g2data dir: "; \
-		echo ""; \
-		echo 'chmod -R 777 $(G2DATA)/locale'; \
-		echo ""; \
-		echo "Alternatively, point your browser at gallery2/lib/support, "; \
-		echo "click the \"Filesystem Permissions\" link and then click "; \
-		echo "the 'Make the locale folder read/write' link"; \
-		echo "************************************************************"; \
+	    echo "************************************************************"; \
+	    echo "WARNING: Failed to copy some .mo files to the g2data/locale"; \
+	    echo "directory! Try changing the permissions on your g2data dir: "; \
+	    echo ""; \
+	    echo 'chmod -R 777 $(G2DATA)/locale'; \
+	    echo ""; \
+	    echo "Alternatively, point your browser at gallery2/lib/support, "; \
+	    echo "click the \"Filesystem Permissions\" link and then click "; \
+	    echo "the 'Make the locale folder read/write' link"; \
+	    echo "************************************************************"; \
 	fi; \
 	if test $${FAIL} -gt 0; then exit 1; fi;
 	@echo '';
@@ -173,25 +171,25 @@ install: check-g2data update
 compendium: messages.po
 	@perl -pi -e 's|^("Content-Type: text/plain; charset)=CHARSET|$$1=UTF-8|' messages.po
 	@for POFILE in `ls $(PO).po | grep -v messages.po`; do \
-		echo -n "$${POFILE} "; \
-		COMPENDIUM=; \
-		for SRC in `ls $(TOOLDIR)/../../*/*/po/$${POFILE} $(TOOLDIR)/../../*/po/$${POFILE}`; \
-		do \
+	    echo -n "$${POFILE} "; \
+	    COMPENDIUM=; \
+	    for SRC in `ls $(TOOLDIR)/../../*/*/po/$${POFILE} $(TOOLDIR)/../../*/po/$${POFILE}`; \
+	    do \
 		COMPENDIUM="$${COMPENDIUM} -C $${SRC}"; \
-		done; \
-		msgmerge --width=95 -N $${COMPENDIUM} \
-			 --suffix= --update $${POFILE} messages.po; \
-		if [ `svn diff $${POFILE} | wc -l` -lt 16 ]; then \
+	    done; \
+	    msgmerge --width=95 -N $${COMPENDIUM} \
+		     --suffix= --update $${POFILE} messages.po; \
+	    if [ `svn diff $${POFILE} | wc -l` -lt 16 ]; then \
 		svn revert --quiet $${POFILE}; \
-		fi; \
+	    fi; \
 	done;
 
 create-from-core:
 	@for POFILE in `ls $(TOOLDIR)/../../modules/core/po/$(PO).po | grep -v messages.po`; do \
-		PO=`basename $${POFILE}`; \
-		if [ ! -f $${PO} ]; then \
+	    PO=`basename $${POFILE}`; \
+	    if [ ! -f $${PO} ]; then \
 		perl -p -e '$$x++ if /^msgid/; exit if $$x eq 2' $${POFILE} > $${PO}; \
-		fi; \
+	    fi; \
 	done;
 
 remove-obsolete:
