Update pre-commit hook

diff --git a/dev_scripts/git-hooks/pre-commit b/dev_scripts/git-hooks/pre-commit
--- a/dev_scripts/git-hooks/pre-commit
+++ b/dev_scripts/git-hooks/pre-commit
@@ -1,17 +1,17 @@
 #!/bin/sh
 
-# Maintenance Item 
+# Maintenance Item
 # find . -type f -print0 | xargs -0 chmod +x
 
-EMPTY_TREE=`printf '' | git hash-object --stdin -t tree`
-PHP_CBF_BIN="./composer_vendor/squizlabs/php_codesniffer/bin/phpcbf"
+EMPTY_TREE=$(printf '' | git hash-object --stdin -t tree)
+PHP_CBF_BIN="./composer_vendor/bin/phpcbf"
 PHP_CBF_CONFIG="./phpcs.xml"
 
-PHP_FIXER_BIN="./composer_vendor/friendsofphp/php-cs-fixer"
+PHP_FIXER_BIN="./composer_vendor/bin/php-cs-fixer"
 PHP_FIXER_CONFIG="./.php_cs.dist"
 
-PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
-STAGED_PHP_FILES=`git diff-index --diff-filter=ACMRT --cached --name-only HEAD -- | egrep '\.php$|\.inc$|\.class$`
+PROJECT=$(php -r "echo dirname(dirname(dirname(realpath('$0'))));")
+STAGED_PHP_FILES=$(git diff-index --diff-filter=ACMRT --cached --name-only HEAD -- | egrep '\.php$|\.inc$|\.class$')
 
 # Determine if file list present
 if [ "$#" -eq 1 ]
@@ -19,33 +19,42 @@ then
 	oIFS=$IFS
 	IFS='
 	'
-	SFILES="$1"
+	TFILES="$1"
 	IFS=$oIFS
 fi
-SFILES=${SFILES:-$STAGED_PHP_FILES}
+SFILES=${TFILES:-$STAGED_PHP_FILES}
 
-if [ "$FILES" == "" ]; then
-	echo "No PHP Files in Commit ... Skip PHP Lint"
+if [ "$SFILES" == "" ]; then
+	echo ""
+	echo "No PHP Files in this Commit ... Skipping PHP Lint"
+	echo ""
 else
+	echo ""
 	echo "PHP Lint Start..."
 	for FILE in $SFILES
 	do
 		php -l -d display_errors=0 $PROJECT/$FILE
 		if [ $? != 0 ]
 		then
-			echo "PHP Lint Errors Found ... Please Fix Before Commit."
+			echo "Please Fix PHP Lint Errors Before Commit"
+			echo ""
+			echo "Unstaging " $PROJECT/$FILE
+			git reset HEAD $PROJECT/$FILE
+			echo ""
 			exit 1
 		fi
-		FILES="$FILES $PROJECT/$FILE"
 	done
-	echo "PHP Lint End"
+	echo "No PHP Lint Errors Found"
 fi
 
 if git rev-parse --verify HEAD
 then
+	echo "Normal commit: diff against HEAD"
+	echo ""
     against=HEAD
 else
-    # Initial commit: diff against an empty tree object
+    echo "Initial commit: diff against an empty tree object"
+	echo ""
 	#against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
     against=$EMPTY_TREE
 fi
@@ -53,10 +62,12 @@ fi
 # Check if PHP_FIXER and PHP_CBF are set up correctly
 if [ ! -x $PHP_FIXER_BIN ]; then
 	echo "ERROR: PHP_FIXER not Found or not Executable ... Aborting"
+	echo ""
 	exit 1
 else
 	if [ ! -x $PHP_CBF_BIN ]; then
     	echo "ERROR: PHP_CBF not Found or not Executable ... Aborting"
+		echo ""
 		exit 1
 	else
 		# Retrieve staged files that were added, modified or renamed but no deletions etc
@@ -64,16 +75,20 @@ else
 
 		if [ "$STAGED_FILES" == "" ]; then
 			echo "ERROR: Unable to Find Staged Files ... Aborting"
+			echo ""
 			exit 1
 		else
 			# Execute PHP_CBF
 			echo "Running PHP_CBF..."
-			OUTPUT=$($PHP_CBF_BIN --standard=$PHP_CBF_CONFIG --file-list=$STAGED_FILES)
+			OUTPUT=$($PHP_CBF_BIN --standard=$PHP_CBF_CONFIG $STAGED_FILES)
 			RETVAL=$?
 			if [ $RETVAL -ne 0 ]; then
 				# Update staged files
 	    		git add $STAGED_FILES
-				echo "$OUTPUT" | less
+			else
+				echo "PHP_CBF ERROR ... Aborting"
+				echo ""
+				exit 1
 			fi
 		fi
 
@@ -81,6 +96,7 @@ else
 		CHANGED_FILES=$(git diff-index --name-only --cached --diff-filter=ACMR $against -- )
 		if [ "$CHANGED_FILES" == "" ]; then
 			echo "The commit has been reset by PHP_CBF"
+			echo ""
 			exit 0
 		else
 			# Execute PHP_FIXER to reverse PHP_CBF issues
@@ -90,10 +106,14 @@ else
 			if [ $RETVAL -ne 0 ]; then
 				# Update staged files
 				git add $CHANGED_FILES
-				echo "$OUTPUT" | less
+			else
+				echo "PHP_FIXER ERROR ... Aborting"
+				echo ""
+				exit 1
 			fi
 		fi
 
-		echo "Commit amended by PHP_CBF & PHP_FIXER_BIN as required"
+		echo "Commit amended by PHP_CBF & PHP_FIXER as required"
+		echo ""
 	fi
 fi
