Fix Format

diff --git a/dev_scripts/hooks/pre-commit b/dev_scripts/hooks/pre-commit
--- a/dev_scripts/hooks/pre-commit
+++ b/dev_scripts/hooks/pre-commit
@@ -8,47 +8,8 @@ PHP_FIX_BIN=dev_vendor/bin/php-cs-fixer
 PHP_FIX_CONFIG=.php_cs.dist
 
 PROJECT=$(php -r "echo dirname(dirname(dirname(realpath('$0'))));")
-STAGED_PHP_FILES=$(git diff-index --name-only --cached --diff-filter=ACMRT HEAD -- | egrep '\.php$|\.inc$|\.class$')
-STAGED_FIX_FILES=$(git diff-index --name-only --cached --diff-filter=ACMRT HEAD -- | egrep '\.php$|\.inc$|\.class$|\.css$|\.js$|\.xml$|\.xaml$|\.html$')
-
-# Get file list
-if [ "$#" -eq 1 ]
-then
-	oIFS=$IFS
-	IFS='
-	'
-	FILE_LIST="$1"
-	IFS=$oIFS
-fi
-
-# Filter file list
-PHP_FILES=${FILE_LIST:-$STAGED_PHP_FILES}
-ALL_FILES=${FILE_LIST:-$STAGED_FIX_FILES}
-
-# Lint PHP files if present
-if [ "$PHP_FILES" != "" ]
-then
-	echo ""
-	echo "Running PHP Lint ..."
-	echo ""
-	for PHP_FILE in $PHP_FILES
-	do
-		FILE="$PROJECT/$PHP_FILE"
-		RET=$(php -l -d display_errors=0 $FILE)
-		if [ $? != 0 ]
-		then
-			echo ""
-			echo "PHP Syntax Errors Found ... Aborting"
-			echo ""
-			RET=$(git reset HEAD $FILE)
-			echo ""
-			echo "Please Fix Errors and Repeat Commit"
-			echo "Remember to Run 'git add $FILE' before Repeating the Commit"
-			echo ""
-			exit 1
-		fi
-	done
-fi
+PHP_FILES=$(git diff-index --name-only --cached --diff-filter=ACMRT HEAD -- | egrep '\.php$|\.inc$|\.class$')
+FIX_FILES=$(git diff-index --name-only --cached --diff-filter=ACMRT HEAD -- | egrep '\.php$|\.inc$|\.class$|\.css$|\.js$|\.xml$|\.xaml$|\.html$')
 
 # Check if PHP-CS-FIXER is set up correctly
 if [ ! -x $PHP_FIX_BIN ]
@@ -68,13 +29,38 @@ else
 		echo ""
 		exit 1
 	else
+		# Lint PHP files if present
+		if [ "$PHP_FILES" != "" ]
+		then
+			echo ""
+			echo "Running PHP Lint ..."
+			echo ""
+			for PHP_FILE in $PHP_FILES
+			do
+				FILE="$PROJECT/$PHP_FILE"
+				RET=$(php -l -d display_errors=0 $FILE)
+				if [ $? != 0 ]
+				then
+					echo ""
+					echo "PHP Syntax Errors Found ... Aborting"
+					echo ""
+					RET=$(git reset HEAD $FILE)
+					echo ""
+					echo "Please Fix Errors and Repeat Commit"
+					echo "Remember to Run 'git add $FILE' before Repeating the Commit"
+					echo ""
+					exit 1
+				fi
+			done
+		fi
+
 		# Execute PHPCBF & PHP-CS-FIXER
 		echo ""
 		echo ""
 		echo "Fixing Coding Style ..."
 		echo ""
 
-		for TARGET_FILE in $ALL_FILES
+		for TARGET_FILE in $FIX_FILES
 		do
 			FILE="$PROJECT/$TARGET_FILE"
 			# Unstage target file
@@ -89,7 +75,7 @@ else
 			# 03. Add blank line after "static $XYZ" calls
 			RET=$(perl -i -pe 's/^(\s*)static ([^;]+;)(\s*)$/$1static $2$3\n\n/' $FILE)
 			# 04. Add blank line before and after "$XYZ->" calls
-			RET=$(perl -i -pe 's/^(\s*)(\$[^-=]+->)([^;]+;)(\s*)$/\n\n$1$2$3$4\n\n/' $FILE)
+			RET=$(perl -i -pe 's/^([^=]*\$)([^-=]+->)([^\)=]+\))([^;]*;)(.*)$/\n\n$1$2$3$4$5\n\n/' $FILE)
 			# 05. Add blank line before "$query" calls
 			RET=$(perl -i -pe 's/^(\s*)\$query\s*(\.?=)/\n\n$1\$query $2/' $FILE)
 			# 06. Add blank line before "$ret" calls
@@ -130,25 +116,25 @@ else
 			RET=$(perl -i -0pe 's/([^\w]+)(\/\/[^\n]+\n)(\s*\n){1,}/$1$2/gs' $FILE)
 			RET=$(perl -i -0pe 's/([^\w]+)(\/\/[^\n]+\n)(\s*\n){1,}/$1$2/gs' $FILE)
 			# 23. Remove blank lines between consecutive $XYZ->" calls
-			RET=$(perl -i -0pe 's/(\s*)(\$[^-=]+->)([^;]+;)(\s*\n\s*){1,}(\n\s*)(\$[^-]+->)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(\$[^-=]+->)([^;]+;)(\s*\n\s*){1,}(\n\s*)(\$[^-]+->)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(\$[^-=]+->)([^;]+;)(\s*\n\s*){1,}(\n\s*)(\$[^-]+->)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(\$[^-=]+->)([^;]+;)(\s*\n\s*){1,}(\n\s*)(\$[^-]+->)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)([^=]*\$)([^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n([^=]*\$)([^-=]+->)([^=\n]+\n)/$1$2$3$4\n$6$7$8$9\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)([^=]*\$)([^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n([^=]*\$)([^-=]+->)([^=\n]+\n)/$1$2$3$4\n$6$7$8$9\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)([^=]*\$)([^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n([^=]*\$)([^-=]+->)([^=\n]+\n)/$1$2$3$4\n$6$7$8$9\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)([^=]*\$)([^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n([^=]*\$)([^-=]+->)([^=\n]+\n)/$1$2$3$4\n$6$7$8$9\n/gs' $FILE)
 			# 24. Remove blank lines between consecutive "global $XYZ" calls
-			RET=$(perl -i -0pe 's/(\s*)(global)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(global)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(global)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(global)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(global)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(global)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(global)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(global)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
 			# 25. Remove blank lines between consecutive "static $XYZ" calls
-			RET=$(perl -i -0pe 's/(\s*)(static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(static)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(static)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(static)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(static)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(static)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(static)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(static)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(static)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
 			# 26. Remove blank lines between consecutive calls to "Gallery" static mathods
-			RET=$(perl -i -0pe 's/(\s*)(Gallery[^:]+::)([^;]+;)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(Gallery[^:]+::)([^;]+;)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(Gallery[^:]+::)([^;]+;)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
-			RET=$(perl -i -0pe 's/(\s*)(Gallery[^:]+::)([^;]+;)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^\n]+\n)/$1$2$3$5$6$7/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(Gallery[^:]+::)([^;]+;)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(Gallery[^:]+::)([^;]+;)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(Gallery[^:]+::)([^;]+;)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
+			RET=$(perl -i -0pe 's/(\n\s*)(Gallery[^:]+::)([^;]+;)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^\n]+\n)/$1$2$3$5$6$7\n/gs' $FILE)
 			# 27. Remove blank lines before closing braces
 			RET=$(perl -i -0pe 's/(\s*\n\s*){1,}(\n\s*)\}/$2\}/gs' $FILE)
 			RET=$(perl -i -0pe 's/(\s*\n\s*){1,}(\n\s*)\}/$2\}/gs' $FILE)
@@ -161,10 +147,10 @@ else
 			RET=$(perl -i -0pe 's/(\s*)\*\/(\n\s*)\/\*/$1\*\/\n\n$2\/\*/gs' $FILE)
 			RET=$(perl -i -0pe 's/(\s*)\*\/(\n\s*)\/\*/$1\*\/\n\n$2\/\*/gs' $FILE)
 			# 29. Remove blank lines after switch case
-			RET=$(perl -i -0pe 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([\/\w])/$1$3$4/gs' $FILE)
-			RET=$(perl -i -0pe 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([\/\w])/$1$3$4/gs' $FILE)
-			RET=$(perl -i -0pe 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([\/\w])/$1$3$4/gs' $FILE)
-			RET=$(perl -i -0pe 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([\/\w])/$1$3$4/gs' $FILE)
+			RET=$(perl -i -0pe 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gs' $FILE)
+			RET=$(perl -i -0pe 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gs' $FILE)
+			RET=$(perl -i -0pe 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gs' $FILE)
+			RET=$(perl -i -0pe 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gs' $FILE)
 			# 30. Remove excess blank lines
 			RET=$(perl -i -0pe 's/(\n\s*){2,}(\n\s*)/\n$2/gs' $FILE)
 			RET=$(perl -i -0pe 's/(\n\s*){2,}(\n\s*)/\n$2/gs' $FILE)
