Update Dev Env

diff --git a/dev_scripts/hooks/pre-commit b/dev_scripts/hooks/pre-commit
--- a/dev_scripts/hooks/pre-commit
+++ b/dev_scripts/hooks/pre-commit
@@ -14,55 +14,49 @@ FIX_FILES=$(git diff-index --name-only --cached --diff-filter=ACMRT HEAD -- | eg
 # Check if PHP-CS-FIXER is set up correctly
 if [ ! -x $PHP_FIX_BIN ]
 then
-	echo ""
-	echo ""
-	echo "PHP-CS-FIXER not Found or not Executable ... Aborting"
-	echo ""
+	echo "\n\nPHP-CS-FIXER not Found or not Executable ... Aborting\n"
 	exit 1
 else
 	# Check if PHPCBF is set up correctly
 	if [ ! -x $PHP_CBF_BIN ]
 	then
-		echo ""
-		echo ""
-   		echo "PHPCBF not Found or not Executable ... Aborting"
-		echo ""
+   		echo "\n\nPHPCBF not Found or not Executable ... Aborting\n"
 		exit 1
 	else
 		# Lint PHP files if present
 		if [ "$PHP_FILES" != "" ]
 		then
-			echo ""
-			echo "Running PHP Lint ..."
-			echo ""
+			echo "\nChecking for PHP syntax errors...\n"
+
 			for PHP_FILE in $PHP_FILES
 			do
 				FILE="$PROJECT/$PHP_FILE"
+
+				echo "...in: $FILE\n"
+
 				RET=$(php -l -d display_errors=0 $FILE)
 				if [ $? != 0 ]
 				then
-					echo ""
-					echo "PHP Syntax Errors Found ... Aborting"
-					echo ""
+					echo "\n\nPHP Syntax Errors Found ... Aborting\n\n"
 					RET=$(git reset HEAD $FILE)
-					echo ""
-					echo "Please Fix Errors and Repeat Commit"
-					echo "Remember to Run 'git add $FILE' before Repeating the Commit"
-					echo ""
+					echo "\n\nPlease Fix Errors and Repeat Commit"
+					echo "Remember to Run 'git add $FILE' before Repeating the Commit\n\n"
 					exit 1
 				fi
 			done
+			echo "\nLinted PHP Files...No syntax errors found"
+
 		fi
 
 		# Execute PHPCBF & PHP-CS-FIXER
-		echo ""
-		echo ""
-		echo "Fixing Coding Style ..."
-		echo ""
+		echo "Apply Coding Style"
 
 		for TARGET_FILE in $FIX_FILES
 		do
 			FILE="$PROJECT/$TARGET_FILE"
+
+			echo "\n\n\nProcessing $FILE\n"
+
 			# Unstage target file
 			RET=$(git reset HEAD $FILE)
 
@@ -79,119 +73,155 @@ else
 			RET=$(perl -p -i -e 's/^(\s*)([^\}]+\})(\s*)(\/\*[^\*]+\*\/)([^\n]+\n)/\n$1$2\n$1$4$5\n/' $FILE)
 			# 04. Remove all blank lines
 			RET=$(perl -p -i -e 's/^\s*$//' $FILE)
-			# 05. Add blank lines before and after "global", "static", "return", "break", "require" and "include" calls
-			RET=$(perl -p -i -e 's/^(\s*)(global|static|return|break|require|include)([^;]*;)(.*)$/\n\n$1$2$3$4\n\n/' $FILE)
-			# 06. Add blank line before "$query", "$ret" and "list" calls
+			# 05. Add blank lines before and after single line "global", "static", "return", "break", "continue" "require" and "include" calls
+			RET=$(perl -p -i -e 's/^(\s*)(global|static|return|break|continue|require|include)([^;]*;)(.*)$/\n\n$1$2$3$4\n\n/' $FILE)
+			# 06. Add blank line before other "global", "static", "return", "break", "continue" "require" and "include" calls
+			RET=$(perl -p -i -e 's/^(\s*)(global|static|return|break|continue|require|include)([^\n]+\n)/\n\n$1$2$3/' $FILE)
+			# 07. Add blank line before "$query", "$ret" and "list" calls
 			RET=$(perl -p -i -e 's/^(\s*)(\$query\s+\.?=|\$ret\s*=|list\()/\n\n$1$2/' $FILE)
-			# 07. Add blank line after single line "$query", "$ret" and "list" calls
+			# 08. Add blank line after single line "$query", "$ret" and "list" calls
 			RET=$(perl -p -i -e 's/^(\s*)(\$query\s+\.?=|\$ret\s+=|list\()([^;]+;)(.*)/$1$2$3$4\n\n/' $FILE)
-			# 08. Add blank line after closing braces
+			# 09. Add blank line after closing braces
 			RET=$(perl -p -i -e 's/^(\s*)\}(\s*)$/$1\}$2\n\n/' $FILE)
-			# 09. Add blank lines before and after "require" and "include" calls
+			# 10. Add blank lines before and after "require" and "include" calls
 			RET=$(perl -p -i -e 's/^(\s*)(require|include)([^;]+;)(.*)$/\n\n$1$2$3$4\n\n/' $FILE)
-			# 10. Add blank line after closing multiline statements and strings
+			# 11. Add blank line after closing multiline statements and strings
 			RET=$(perl -p -i -e 's/^(\s*)(\)|\x27|");(\s*)$/$1$2;$3\n\n/' $FILE)
-			# 11. Add blank line before single line comments
+			# 12. Add blank line before single line comments
 			RET=$(perl -p -i -e 's/^(\s*)(\/\/.+?)/\n\n$1$2/' $FILE)
-			# 12.  Add blank line before multi line comments
+			# 13.  Add blank line before multi line comments
 			RET=$(perl -p -i -e 's/^(\s*)\/\*/\n\n$1\/\*/' $FILE)
-			# 13. Add blank line before opening braces
-			RET=$(perl -p -i -e 's/^(\s*)(.+)([^\{]+\{)\n/\n\n$1$2$3\n/' $FILE)
-			RET=$(perl -p -i -e 's/^(\s*)(if)(\s+\()([^\n]+\n)/\n\n$1$2$3$4/' $FILE)
-			# 14. Remove blank single line comments
+			# 14. Add blank line before opening braces
+			RET=$(perl -p -i -e 's/^(\s*)([^\{\*]+\{)\n/\n\n$1$2\n/' $FILE)
+			RET=$(perl -p -i -e 's/^(\s*)(if|foreach|while)(\s+\()([^\n]+\n)/\n\n$1$2$3$4/' $FILE)
+			# 15. Remove blank single line comments
 			RET=$(perl -p -i -e 's/^(\s*)(\/\/)(\s*)$//' $FILE)
-			# 15. Add blank line before and after "$XYZ->" calls
-			RET=$(perl -p -i -e 's/^([^=]*\$)([^-=]+->)([^\)=]+\))([^;]*;)(.*)$/\n\n$1$2$3$4$5\n\n/' $FILE)
-			# 16. Add blank line before and after calls to "Gallery" static mathods
-			RET=$(perl -p -i -e 's/(\s*)(Gallery[^:]+::)([^;]+;)([^\n]*\n)/\n\n$1$2$3$4\n\n/' $FILE)
-			# 17. Remove blank lines after single line comments
+			# 16. Add blank line before and after single line "$XYZ->" calls
+			RET=$(perl -p -i -e 's/^([^=\.\?\:\/\*\(]*\$)([^-=]+->)([^\)=]+\))([^=;]*;)(.*)$/\n\n$1$2$3$4$5\n\n/' $FILE)
+			# 17. Add blank line before other "$XYZ->" calls
+			RET=$(perl -p -i -e 's/^([^=\.\?\:\/\*\(]*\$)([^-=]+->)([^\)=]+\()([^=\n]*\n)/\n\n$1$2$3$4/' $FILE)
+			# 18. Add blank line before and after calls to static mathods
+			RET=$(perl -p -i -e 's/^([^=\$\.\?\:\/\*\(]*::)([^;]+;)([^\n]*\n)/\n\n$1$2$3\n\n/' $FILE)
+			# 19. Add blank line before switch case statements
+			RET=$(perl -p -i -e 's/^(\s*)(case|default)([^:]+:)(.*)$/$1$2$3$4\n\n/' $FILE)
+			# 20. Remove blank lines after single line comments
 			RET=$(perl -0777 -p -i -e 's/([^\w]+)(\/\/[^\n]+\n)(\s*\n){1,}/$1$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^\w]+)(\/\/[^\n]+\n)(\s*\n){1,}/$1$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^\w]+)(\/\/[^\n]+\n)(\s*\n){1,}/$1$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^\w]+)(\/\/[^\n]+\n)(\s*\n){1,}/$1$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^\w]+)(\/\/[^\n]+\n)(\s*\n){1,}/$1$2/gms' $FILE)
-			# 18. Add blank line after closing braces with single line comments
+			# 21. Add blank line after closing braces with single line comments
 			RET=$(perl -p -i -e 's/^(\s*)([^\}]+\})(\s*)(\/\/[^\n]+\n)/$1$2 $4\n\n/' $FILE)
 			RET=$(perl -p -i -e 's/^(\s*)([^\}]+\})(\s*)(\/\*[^\*]+\*\/)([^\n]+\n)/$1$2 $4$5\n\n/' $FILE)
-			# 19. Remove blank lines after multiline comments
+			# 22. Remove blank lines after multiline comments
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*\n)/$1$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*\n)/$1$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*\n)/$1$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*\n)/$1$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*\n)/$1$2/gms' $FILE)
-			# 20. Add blank line between multi and single line comments
+			# 23. Add blank line between multi and single line comments
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*)(\/\/)/$1$2\n$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*)(\/\/)/$1$2\n$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*)(\/\/)/$1$2\n$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*)(\/\/)/$1$2\n$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/[^\n]*\n)(\s*)(\/\/)/$1$2\n$3$4/gms' $FILE)
-			# 21. Add blank line between single and multi line comments
+			# 24. Add blank line between single and multi line comments
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\/\/[^\n]+\n)(\s*)(\/\*[^\n]*\n)/$1$2\n\n$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\/\/[^\n]+\n)(\s*)(\/\*[^\n]*\n)/$1$2\n\n$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\/\/[^\n]+\n)(\s*)(\/\*[^\n]*\n)/$1$2\n\n$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\/\/[^\n]+\n)(\s*)(\/\*[^\n]*\n)/$1$2\n\n$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\/\/[^\n]+\n)(\s*)(\/\*[^\n]*\n)/$1$2\n\n$3$4/gms' $FILE)
-			# 22. Remove blank lines between consecutive calls to "Gallery" static mathods
-			RET=$(perl -0777 -p -i -e 's/(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*\n)/$1$2$3$4$6$7$8$9/gms' $FILE)
-			RET=$(perl -0777 -p -i -e 's/(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*\n)/$1$2$3$4$6$7$8$9/gms' $FILE)
-			RET=$(perl -0777 -p -i -e 's/(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*\n)/$1$2$3$4$6$7$8$9/gms' $FILE)
-			RET=$(perl -0777 -p -i -e 's/(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*\n)/$1$2$3$4$6$7$8$9/gms' $FILE)
-			RET=$(perl -0777 -p -i -e 's/(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)(Gallery[^:]+::)([^;]+;)([^\n]*\n)/$1$2$3$4$6$7$8$9\n/gms' $FILE)
-			# 23. Remove blank lines after switch case
+			# 25. Remove blank lines after final colons
 			RET=$(perl -0777 -p -i -e 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^:]+:)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
-			# 24. Remove blank lines between consecutive "$XYZ->" calls
+			# 26. Remove blank lines after final commas
+			RET=$(perl -0777 -p -i -e 's/([^,]+,)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^,]+,)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^,]+,)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^,]+,)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^,]+,)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			# 27. Remove blank lines between consecutive calls to static mathods
+			RET=$(perl -0777 -p -i -e 's/(\n[^=\$\.\?\:\/\*]*::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)([^=\$\.\?\:\/\*]+::)([^;]+;)([^\n]*\n)/$1$2$3$5$6$7$8/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\n[^=\$\.\?\:\/\*]*::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)([^=\$\.\?\:\/\*]+::)([^;]+;)([^\n]*\n)/$1$2$3$5$6$7$8/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\n[^=\$\.\?\:\/\*]*::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)([^=\$\.\?\:\/\*]+::)([^;]+;)([^\n]*\n)/$1$2$3$5$6$7$8/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\n[^=\$\.\?\:\/\*]*::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)([^=\$\.\?\:\/\*]+::)([^;]+;)([^\n]*\n)/$1$2$3$5$6$7$8/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\n[^=\$\.\?\:\/\*]*::)([^;]+;)([^\n]*)(\s*\n\s*){1,}(\n\s*)([^=\$\.\?\:\/\*]+::)([^;]+;)([^\n]*\n)/$1$2$3$5$6$7$8/gms' $FILE)
+			# 28. Remove blank lines between consecutive "$XYZ->" calls
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(\$[^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n(\s*)(\$[^-=]+->)([^=;]+;)/$1$2$3\n$5$6$7/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(\$[^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n(\s*)(\$[^-=]+->)([^=;]+;)/$1$2$3\n$5$6$7/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(\$[^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n(\s*)(\$[^-=]+->)([^=;]+;)/$1$2$3\n$5$6$7/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(\$[^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n(\s*)(\$[^-=]+->)([^=;]+;)/$1$2$3\n$5$6$7/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(\$[^-=]+->)([^=;]+;)(\s*\n\s*){1,}\n(\s*)(\$[^-=]+->)([^=;]+;)/$1$2$3\n$5$6$7\n/gms' $FILE)
-			# 25. Remove blank lines between consecutive "global" and "static" $XYZ calls
+			# 29. Remove blank lines between consecutive "global" and "static" $XYZ calls
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global|static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global|static)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global|static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global|static)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global|static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global|static)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global|static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global|static)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global|static)([^;]+;)(\s*\n\s*){1,}(\n\s*)(global|static)([^\n]+\n)/$1$2$3$5$6$7\n/gms' $FILE)
-			# 26. Combine consecutive "global" $XYZ calls
+			# 30. Remove blank lines between consecutive "require" and "include" calls
+			RET=$(perl -0777 -p -i -e 's/(\n\s*)(require|include)([^;]+;)(\s*\n\s*){1,}(\n\s*)(require|include)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\n\s*)(require|include)([^;]+;)(\s*\n\s*){1,}(\n\s*)(require|include)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\n\s*)(require|include)([^;]+;)(\s*\n\s*){1,}(\n\s*)(require|include)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\n\s*)(require|include)([^;]+;)(\s*\n\s*){1,}(\n\s*)(require|include)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\n\s*)(require|include)([^;]+;)(\s*\n\s*){1,}(\n\s*)(require|include)([^\n]+\n)/$1$2$3$5$6$7/gms' $FILE)
+			# 31. Combine consecutive "global" $XYZ calls
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global)([^;]+)(;)(\n\s*)(global)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global)([^;]+)(;)(\n\s*)(global)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global)([^;]+)(;)(\n\s*)(global)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global)([^;]+)(;)(\n\s*)(global)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(global)([^;]+)(;)(\n\s*)(global)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
-			# 27. Combine consecutive "static" $XYZ calls
+			# 32. Combine consecutive "static" $XYZ calls
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(static)([^;]+)(;)(\n\s*)(static)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(static)([^;]+)(;)(\n\s*)(static)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(static)([^;]+)(;)(\n\s*)(static)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(static)([^;]+)(;)(\n\s*)(static)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*)(static)([^;]+)(;)(\n\s*)(static)([^;]+;)([^\n]*\n)/$1$2$3, $7$8/gms' $FILE)
-			# 29. Separate multiline comment blocks
+			# 33. Separate multiline comment blocks
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/)\s*\n*(\s*\/\*)/$1$2\n\n$3/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/)\s*\n*(\s*\/\*)/$1$2\n\n$3/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/)\s*\n*(\s*\/\*)/$1$2\n\n$3/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/)\s*\n*(\s*\/\*)/$1$2\n\n$3/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*)(\*\/)\s*\n*(\s*\/\*)/$1$2\n\n$3/gms' $FILE)
-			# 29. Remove blank lines before closing braces
+			# 34. Remove blank lines before closing braces
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)\}/$2\}/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)\}/$2\}/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)\}/$2\}/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)\}/$2\}/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)\}/$2\}/gms' $FILE)
-			# 30. Remove blank lines before else statements
+			# 35. Remove blank lines before else statements
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\}|\))([^\{]+\{)([^\n]*\n)/$2$3$4$5\n/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\}|\))([^\{]+\{)([^\n]*\n)/$2$3$4$5\n/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\}|\))([^\{]+\{)([^\n]*\n)/$2$3$4$5\n/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\}|\))([^\{]+\{)([^\n]*\n)/$2$3$4$5\n/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\}|\))([^\{]+\{)([^\n]*\n)/$2$3$4$5\n/gms' $FILE)
-			# 31. Remove blank lines after opening braces
+			# 36. Remove blank lines after opening braces
 			RET=$(perl -0777 -p -i -e 's/([^\{]+\{)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^\{]+\{)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^\{]+\{)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^\{]+\{)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/([^\{]+\{)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
-			# 32. Remove excess blank lines
+			# 37. Remove blank lines after opening brackets
+			RET=$(perl -0777 -p -i -e 's/([^\(]+\()(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^\(]+\()(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^\(]+\()(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^\(]+\()(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^\(]+\()(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			# 38. Remove blank lines after ending full stop
+			RET=$(perl -0777 -p -i -e 's/([^\.]+\.)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^\.]+\.)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^\.]+\.)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^\.]+\.)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/([^\.]+\.)(\s*\n\s*){1,}(\n\s*)([^\n]+\n)/$1$3$4/gms' $FILE)
+			# 39. Remove blank lines before "if" continuation operators
+			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\&\&|\|\|)/$2$3/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\&\&|\|\|)/$2$3/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\&\&|\|\|)/$2$3/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\&\&|\|\|)/$2$3/gms' $FILE)
+			RET=$(perl -0777 -p -i -e 's/(\s*\n\s*){1,}(\n\s*)(\&\&|\|\|)/$2$3/gms' $FILE)
+			# 40. Compress multiple blank lines
 			RET=$(perl -0777 -p -i -e 's/(\n\s*){2,}(\n\s*)/\n$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*){2,}(\n\s*)/\n$2/gms' $FILE)
 			RET=$(perl -0777 -p -i -e 's/(\n\s*){2,}(\n\s*)/\n$2/gms' $FILE)
@@ -211,6 +241,15 @@ else
 			# 02. Close empty braces on same line as opening brace
 			RET=$(perl -i -0pe 's/\{\s*\n\s*\}([^\w]*)/{}$1/gms' $FILE)
 
+			# Ensure syntax errors have not been introduced
+			RET=$(php -l -d display_errors=0 $FILE)
+			if [ $? != 0 ]
+			then
+				echo "\n\nPHP Errors introduced by pre-commit script ... Aborting"
+				echo "Please raise an issue on https://github.com/dakanji/G2Project/issues\n\n"
+				exit 1
+			fi
+
 
 			# Stage target file
 			git add $FILE
@@ -221,17 +260,11 @@ else
 
 		if [ "$RET" == "" ]
 		then
-			echo ""
-			echo "NOTE: Commit Emptied After Style Fix ... Aborting"
-			echo ""
+			echo "\nNOTE: Commit Emptied After Style Fix ... Aborting\n"
 			exit 1
 		fi
 
 		# Completed
-		echo ""
-		echo ""
-		echo "Coding Style Fixed"
-		echo ""
-		echo ""
+		echo "\n\nCoding Style Fixed\n\n"
 	fi
 fi
